BrolIndexer/Controllers/PersoonController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Data;
using System.Web.Mvc;
using BrolIndexer.Models;
using BrolIndexer.Services;

namespace BrolIndexer.Controllers
{
    public class PersoonController : Controller
    {
        HerstellingenEntities db = new HerstellingenEntities();
        HerstellingService service = new HerstellingService();
        
        [HttpGet]
        [Authorize(Roles = "Technicus, admin")]
        public ActionResult Upload(int id)
        {
            return View(id);
        }

        [HttpPost]
        [Authorize(Roles = "Technicus, admin")]
        public ActionResult FotoUpload(int id)
        {
            if (Request.Files.Count > 0)
            {
                var foto = Request.Files[0];
                foto.SaveAs(Path.Combine(HttpContext.Server.MapPath("~/Content/fotos"),id +".jpg"));
            }
            return RedirectToAction("GeefTechnicusWeer", new{ID=id});
        }

        [Authorize(Roles = "Technicus,Admin")]
        public ActionResult GeefKlantWeer(int id)
        {
            return View(service.GetKlant(id));
        }


        [Authorize(Roles = "Admin,technicus")]
        public ActionResult GeefAlleKlantenWeer()
        {
            return View(service.GetAlleKlanten());
        }

        [Authorize]
        public ActionResult GeefTechnicusWeer(int id)
        {
            return View(service.GetTechnicus(id));
        }

        public ActionResult AllePersoneelWeergeven()
        {
            return View((service.GetAlleTechnici()));
        }

        [Authorize(Roles = "technicus, admin")]
        public ActionResult CreateKlant()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "technicus, admin")]
        public ActionResult CreateKlant(Klant klant)
        {
            if (ModelState.IsValid)
            {
                db.Klanten.Add(klant);
                db.SaveChanges();
                if (Session["BewerkModus"]!=null)
                    System.Web.HttpContext.Current.Session.Remove("BewerkModus");
                    return RedirectToAction("Create", "Herstelling");
                    return RedirectToAction("Index", "Home");
            }
            return View(klant);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            service.Dispose();
            base.Dispose(disposing);
        }
    }
}

BrolIndexer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Stormcreations</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Bedrijfslogo", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Webshop","Index","Webshop")</li>
                            @if (Request.IsAuthenticated)
                            {
                                <li>@Html.ActionLink("Herstellingen", "Index", "Herstelling")</li>
                                
                            }
                            @if (User.IsInRole("Technicus") || User.IsInRole("Admin"))
                                 {
                                     <li>@Html.ActionLink("Klantenbeheer","GeefAlleKlantenWeer","Persoon")</li>
                                 }
                            <li>@Html.ActionLink("Over ons", "About", "Home")</li>
                            <li>@Html.ActionLink("Cast and Crew","AllePersoneelWeergeven","Persoon")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Lieven Vanhercke</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>